export const ARTICLES_LOADING = 'ARTICLES_LOADING';
export const ARTICLES_FAILED = 'ARTICLES_FAILED';
export const ADD_ARTICLES = 'ADD_ARTICLES';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const FAILED_COMMENT = 'FAILED_COMMENT';

export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const ADD_CART = 'ADD_CART';
export const CART_LOADING = 'CART_LOADING';
export const CART_FAILED = 'CART_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_LOADING';

export const ADD_PROMOTION = 'ADD_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';

export const ADD_FAVORITES = 'ADD_FAVORITES';
export const FAVORITES_LOADING = 'FAVORITES_LOADING';
export const FAVORITES_FAILED = 'FAVORITES_FAILED';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';

export const ADD_SLIDERS = 'ADD_SLIDERS';
export const SLIDERS_LOADING = 'SLIDERS_LOADING';
export const SLIDERS_FAILED = 'SLIDERS_FAILED';

